config/routes.rb
Rails.application.routes.draw do
  get 'posts/profile'
  get 'posts/destroy_all'
  get 'users/show'
  devise_for :users
  resources :posts do
     member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
     end
     resources :comments
    end
    root 'posts#index'

  match '/posts',   to: 'posts#profile',   via: 'get'

  match '/posts', to: 'posts#destroy_all', via: 'delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
 class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments ,:dependent => :destroy
  has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts,:dependent => :delete_all
  has_many :comments,:dependent => :destroy

end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
  @post=Post.find(params[:post_id])
  @comment=Comment.create(params[:comment].permit(:content))
  @comment.user_id = current_user.id
  @comment.post_id =@post.id

   if @comment.save
     CommentMailer.new_comment(@comment).deliver!
    redirect_to post_path(@post)
   else
    render 'new'
   end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post,only: [:show,:edit,:update,:destroy,:upvote,:downvote]
  before_action :authenticate_user!,except: [:index,:show]
  def index
    #align all posts in recently created  to old posts
    @posts = Post.all.order("created_at DESC")

  end
  def destroy_all

    GeneratePostJob.perform_now(current_user.id)
    redirect_to posts_profile_path
    end



  def show
    @comments = Comment.where(post_id: @post)


  end
  def profile
    @post = Post.find_by_title(params[:id])
  end
  def new
    #current user checks if there is user id in the post inorder to create new post
    @post=current_user.posts.build
  end

  def create
    #a post can have a only a title, description,link for a current signed up user
    @post=current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def upvote
    @post.upvote_by current_user
    redirect_to post_path
  end

  def downvote
    @post.downvote_by current_user
    redirect_to post_path
  end

  def edit

  end

  def update

    #autofill the title,description,link and any edit and save can be done
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    #delete the current post

    @post.destroy
    redirect_to root_path
  end

  def find
  end



  private

  def find_post
    #find the post with post with post id
    @post=Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title,:link,:description,:image)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%=simple_form_for([@post,@post.comments.build]) do |f| %>


  <%=f.input :content ,label: "Share Your Thoughts : " %>
</p>
  <%=f.button :submit , class: "button " %>

<%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MUSE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" rel="stylesheet">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"></link>
    <%= csrf_meta_tags %>
    </link>
  </head>

  <body>
  <header>
    <div class="wrapper clearfix">
      <div id="logo" style="font-size: 60px">
        <%= link_to "Muse", root_path %>
      </div>
      <nav>
        <% if user_signed_in? %>
          <%= link_to "My Profile", posts_profile_path %>
          <%= link_to "Edit Profile", edit_user_registration_path %>
          <%= link_to "Add New Inspiration", new_post_path, class: "button" %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete ,class: "button"%>
        <% else %>
          <%= link_to "Sign in", new_user_session_path ,class: "button"%>
          <%= link_to "Sign Up", new_user_registration_path, class: "button" %>

        <% end %>
      </nav>
    </div>
  </header>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<html>
<body>
<%= simple_form_for @post do |f| %>

  <div class="form-inputs" style=" padding-right: 200px;width:200px;padding: 5px;font-size: 20px;font-size: 20px;padding-left: 700px">
<%=f.input  :image%><br>
<%= f.input :title %><br>
<%= f.input :description %><br>


    <%= f.button :submit %>
  </div>
<%end %>
</body>
</html>

app/views/posts/edit.html.erb
<h1 style="color: #B00100;font-size: 50px;padding-left: 650px"> Edit Inspiration ! </h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<body >
<% if user_signed_in? %>
  <p id="intro">
    Hello
    <%= current_user.name %>
    <br/>
    <span>
      Share your inspiration and see what's inspiring others.
    </span>
  </p>
<% else %>
  <p id="intro">
    What's your muse?
    <br/>
    <span>
      Share your inspiration and see what's inspiring others.
    </span>
  </p>
<% end %>
<div id="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post_image">
        <%= link_to (image_tag post.image.url(:small)), post %>
      </div>
      <div class="post_content">
        <div class="title">
          <h2>
            <%= link_to post.title, post %>
          </h2>
        </div>
        <div class="data clearfix">
          <p class="username">
            Shared by
            <%= post.user.name %>
          </p>
          <p class="buttons">
            <span>
              <i class="fa fa-comments-o"></i>
              <%= post.comments.count %>
            </span>
            <span>
              <i class="fa fa-thumbs-o-up"></i>
              <%= post.get_likes.size %>
            </span>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>
</body>

app/views/posts/new.html.erb
<html>
<h1 style="color: #B00100;font-size: 50px;padding-left: 600px">Create Your new Inspirations</h1>
<%= render 'form' %>
</html>

app/views/posts/profile.html.erb
<% @posts = Post.where(:user_id => current_user) %>
<p id="intro">
  <i class="fa fa-user"></i>
  <%= current_user.name %>
  &ensp; &ensp; &ensp;
<%= link_to "Delete All",posts_destroy_all_path%>
</p>


<div id="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post_image">
        <%= link_to (image_tag post.image.url(:small)), post %>
      </div>
      <div class="post_content">
        <div class="title">
          <h2>
            <%= link_to post.title, post %>
          </h2>
        </div>
        <div class="data clearfix">
          <p class="buttons">
            <span>
              <i class="fa fa-comments-o"></i>
              <%= post.comments.count %>
            </span>
            <span>
              <i class="fa fa-thumbs-o-up"></i>
              <%= post.get_likes.size %>
            </span>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<% if user_signed_in? %>
  <div id="post_show">
    <h1>
      <%= @post.title %>
    </h1>
    <p class="username">
      Shared by
      <%= @post.user.name %>
      about
      <%= time_ago_in_words(@post.created_at) %>
    </p>
    <div class="clearfix">
      <div class="post_image_description">
        <%= image_tag @post.image.url(:medium) %>
        <div class="description">
          <%= simple_format(@post.description) %>
        </div>
      </div>
      <div class="post_data">
        <%= link_to "Visit Link", @post.link, class: "button" %>
        <%= link_to like_post_path(@post), method: :get, class: "data" do %>
          <i class="fa fa-thumbs-o-up"></i>
          <%= pluralize(@post.get_upvotes.size, "Like") %>
        <% end %>
        <%= link_to dislike_post_path(@post), method: :get, class: "data" do %>
          <i class="fa fa-thumbs-o-down"></i>
          <%= pluralize(@post.get_downvotes.size, "Dislike") %>
        <% end %>
        <p class="data">
          <i class="fa fa-comments-o"></i>
          <%= pluralize(@post.comments.count, "Comment") %>
        </p>
        <% if @post.user == current_user %>
          <%= link_to "Edit", edit_post_path(@post), class: "data" %>
          <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "data" %>
        <% end %>
      </div>

    </div>
  </div>
  <div id="comments">
    <h2 class="comment_count">
      <%= pluralize(@post.comments.count, "Comment") %>
    </h2>
    <% @comments.each do |comment| %>
      <div class="comment">
        <p class="username">
          <%= comment.user.name %>
        </p>
        <p class="content">
          <%= comment.content %>
        </p>
      </div>
    <% end %>
    <%= render "comments/form" %>
  </div>

<% else %>
  <div id="post_show">
    <h1 style="color: #B00100;font-size: 50px;padding-left: 20px">
      <%= @post.title %>
    </h1>
    <p class="username" style="padding-left: 30px">
      <i class="fa fa-user"></i> &ensp;
      <%= @post.user.name %>
      about
      <%= time_ago_in_words(@post.created_at) %>
    </p>
    <div class="clearfix">
      <div class="post_image_description" style="padding-left: 30px" >
        <%= image_tag @post.image.url(:medium) %>
        <div class="description" style="padding-left: 20px;font-size: 20px">
          <%= simple_format(@post.description) %>
        </div>
  </div>
    </div>

      <div class="post_data" style="padding-left: 100px">

        <%= link_to like_post_path(@post), method: :get, class: "data" do %>
          <i class="fa fa-thumbs-o-up"></i>
          <%= pluralize(@post.get_upvotes.size, "Like") %>
        <% end %>
        <%= link_to dislike_post_path(@post), method: :get, class: "data" do %>
          <i class="fa fa-thumbs-o-down"></i>
          <%= pluralize(@post.get_downvotes.size, "Dislike") %>
        <% end %>
        <p class="data">
          <i class="fa fa-comments-o"></i>
          <%= pluralize(@post.comments.count, "Comment") %>
        </p>

      </div>
  </div>
  <p style="padding: 150px ;padding-left: 40px;color: #B00100 ; font-size: 20px"> Sign in or Sign Up to see more ! </p>

<%end %>